name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout  # Automatically uses the latest version

      - name: Set Up Node.js
        uses: actions/setup-node@v3  # Use a specific version

      - name: Install Dependencies
        run: npm install

      - name: Build SvelteKit App
        run: npm run build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v2  # Use a specific version
        with:
          args: deploy --only hosting

env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_SECRET }}
